apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: prod
type: Opaque
stringData:
  DATABASE_URL: "postgres://usuario:senha@host.rds.amazonaws.com:5432/prod_db"
  SECRET_KEY: "chave-prod-super-secreta"
  DJANGO_ALLOWED_HOSTS: "api.seudominio.com"
  DJANGO_DEBUG: "False"
