# overlays/dev/secret-dev.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: app-ns
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXMK
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MDIxMjIwMTVQZWRybw==
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczowMjEyMjAxNVBlZHJvQHBvc3RncmVzLXNlcnZpY2UuYXBwLW5zLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvcG9zdGdyZXMK
  DJANGO_ALLOWED_HOSTS: bG9jYWxob3N0LDEyNy4wLjAuMSwwLjAuMC4wLDEwLjEuMC4xMDA=
  DJANGO_DEBUG: RmFsc2U=
  SECRET_KEY: c3VwZXItc2VjdXJlLXNlY3JldA==