apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: app-ns
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 02122015Pedro
  DATABASE_URL: postgres://postgres:02122015Pedro@postgres:5432/postgres
